name: Example Workflow

on:
  workflow_dispatch:

jobs:
  main_job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Step 1
        run: echo "This is step 1"
        
      - name: Step 2
        run: |
          echo "This is step 2"
          # Simulate a failure
          exit 1

      - name: Step 3 (Manual Intervention)
        if: failure()
        run: |
          echo "Previous step failed. Pausing workflow for manual intervention."
          # Trigger manual intervention, e.g., create an issue
          # Create an issue using GitHub API
          # For example, using curl
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues \
            -d '{"title":"Manual intervention required: Step 2 failed"}'
          # Output a message indicating manual intervention required
          echo "::error::Manual intervention required. Check GitHub issues for details."
          # Exit with success status to pause the workflow
          exit 0

      - name: Step 4
        if: success() || github.event_name == 'workflow_dispatch'
        run: echo "This is step 4"
